#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR=${PROJECT_DIR:-${AGOPD_ROOT}}
cd "${PROJECT_DIR}"

# Isolate performance tuning from the stable 1-GPU-student launcher.
export STUDENT_GPUS=${STUDENT_GPUS:-2}
export TRAIN_STEPS=${TRAIN_STEPS:-3}
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-32}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-32}
export ROLLOUT_N=${ROLLOUT_N:-4}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.50}
export TEACHER_GPU_MEMORY_UTILIZATION=${TEACHER_GPU_MEMORY_UTILIZATION:-0.50}
export ROLLOUT_ENFORCE_EAGER=${ROLLOUT_ENFORCE_EAGER:-False}
export TEACHER_ENFORCE_EAGER=${TEACHER_ENFORCE_EAGER:-False}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-16384}
export TEACHER_MAX_NUM_BATCHED_TOKENS=${TEACHER_MAX_NUM_BATCHED_TOKENS:-16384}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-cloud_perf_smoke}
export TENSORBOARD_DIR=${TENSORBOARD_DIR:-${PROJECT_DIR}/tensorboard/cloud_perf_smoke}
export OUTPUT_DIR=${OUTPUT_DIR:-${PROJECT_DIR}/outputs/cloud_perf_smoke}

exec bash scripts/run_grpo_vanilla_opd.sh "$@"
