#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR=${PROJECT_DIR:-${AGOPD_ROOT}}
VERL_DIR=${VERL_DIR:-${PROJECT_DIR}/verl-v0.8.0-src/verl-v0.8.0}
OPD_PYTHON=${OPD_PYTHON:-${AGOPD_OPD_VENV}/bin/python}
STUDENT_MODEL=${STUDENT_MODEL:-${PROJECT_DIR}/models/Qwen3-1.7B}
TEACHER_MODEL=${TEACHER_MODEL:-${PROJECT_DIR}/models/Qwen3-4B}
TRAIN_FILE=${TRAIN_FILE:-${PROJECT_DIR}/data/dapo-verl-v1/train.parquet}
VAL_FILE=${VAL_FILE:-${PROJECT_DIR}/data/dapo-verl-v1/val.parquet}
TENSORBOARD_DIR=${TENSORBOARD_DIR:-${PROJECT_DIR}/tensorboard/grpo_vanilla_opd_50step}
OUTPUT_DIR=${OUTPUT_DIR:-${PROJECT_DIR}/outputs/grpo_vanilla_opd_50step}
STUDENT_GPUS=${STUDENT_GPUS:-1}
TRAIN_STEPS=${TRAIN_STEPS:-50}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-1000}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-16}
PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-${TRAIN_BATCH_SIZE}}
ROLLOUT_N=${ROLLOUT_N:-2}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.25}
TEACHER_GPU_MEMORY_UTILIZATION=${TEACHER_GPU_MEMORY_UTILIZATION:-0.25}
ROLLOUT_ENFORCE_EAGER=${ROLLOUT_ENFORCE_EAGER:-True}
TEACHER_ENFORCE_EAGER=${TEACHER_ENFORCE_EAGER:-True}
ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-8192}
TEACHER_MAX_NUM_BATCHED_TOKENS=${TEACHER_MAX_NUM_BATCHED_TOKENS:-8192}
TEACHER_N_GPUS=${TEACHER_N_GPUS:-1}
TEACHER_TENSOR_MODEL_PARALLEL_SIZE=${TEACHER_TENSOR_MODEL_PARALLEL_SIZE:-1}
ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-0.6}
ROLLOUT_TOP_P=${ROLLOUT_TOP_P:-0.95}
DISTILLATION_USE_TASK_REWARDS=${DISTILLATION_USE_TASK_REWARDS:-True}
DISTILLATION_COEF=${DISTILLATION_COEF:-1.0}
SAVE_FREQ=${SAVE_FREQ:-10}
STUDENT_PARAM_OFFLOAD=${STUDENT_PARAM_OFFLOAD:-False}
STUDENT_OPTIMIZER_OFFLOAD=${STUDENT_OPTIMIZER_OFFLOAD:-False}
STUDENT_LORA_RANK=${STUDENT_LORA_RANK:-0}
STUDENT_LORA_ALPHA=${STUDENT_LORA_ALPHA:-16}
STUDENT_LORA_MERGE=${STUDENT_LORA_MERGE:-False}

cd "${PROJECT_DIR}"
export PYTHONPATH="${PROJECT_DIR}/src:${VERL_DIR}:${PROJECT_DIR}/verl-v0.8.0-src/verl-v0.8.0:${PYTHONPATH:-}"
export PYTHONPATH="${AGOPD_VLLM_VENV}/lib/python3.12/site-packages:${PYTHONPATH}"
RAY_PYTHONPATH="${PYTHONPATH}"
export VLLM_WORKER_MULTIPROC_METHOD=spawn
export WANDB_MODE=offline
export HYDRA_FULL_ERROR=1
export TENSORBOARD_DIR

"${OPD_PYTHON}" -m verl.trainer.main_ppo \
  algorithm.adv_estimator=grpo \
  algorithm.use_kl_in_reward=False \
  custom_reward_function.path="${PROJECT_DIR}/src/agopd/reward/verl_adapter.py" \
  custom_reward_function.name=compute_score \
  data.train_files="['${TRAIN_FILE}']" \
  data.val_files="['${VAL_FILE}']" \
  data.train_batch_size="${TRAIN_BATCH_SIZE}" \
  data.max_prompt_length=1024 \
  data.max_response_length=2048 \
  data.filter_overlong_prompts=True \
  data.truncation=error \
  data.dataloader_num_workers=0 \
  actor_rollout_ref.model.path="${STUDENT_MODEL}" \
  actor_rollout_ref.model.lora_rank="${STUDENT_LORA_RANK}" \
  actor_rollout_ref.model.lora_alpha="${STUDENT_LORA_ALPHA}" \
  actor_rollout_ref.model.lora.merge="${STUDENT_LORA_MERGE}" \
  +actor_rollout_ref.model.override_config.attn_implementation=sdpa \
  actor_rollout_ref.model.use_remove_padding=False \
  actor_rollout_ref.model.enable_gradient_checkpointing=True \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  actor_rollout_ref.actor.ppo_mini_batch_size="${PPO_MINI_BATCH_SIZE}" \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.actor.use_remove_padding=False \
  actor_rollout_ref.actor.use_kl_loss=True \
  actor_rollout_ref.actor.kl_loss_coef=0.01 \
  actor_rollout_ref.actor.fsdp_config.param_offload="${STUDENT_PARAM_OFFLOAD}" \
  actor_rollout_ref.actor.fsdp_config.optimizer_offload="${STUDENT_OPTIMIZER_OFFLOAD}" \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.nnodes=1 \
  actor_rollout_ref.rollout.n_gpus_per_node=1 \
  actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
  actor_rollout_ref.rollout.n="${ROLLOUT_N}" \
  actor_rollout_ref.rollout.temperature="${ROLLOUT_TEMPERATURE}" \
  actor_rollout_ref.rollout.top_p="${ROLLOUT_TOP_P}" \
  actor_rollout_ref.rollout.top_k=20 \
  actor_rollout_ref.rollout.gpu_memory_utilization="${ROLLOUT_GPU_MEMORY_UTILIZATION}" \
  actor_rollout_ref.rollout.enforce_eager="${ROLLOUT_ENFORCE_EAGER}" \
  actor_rollout_ref.rollout.max_num_batched_tokens="${ROLLOUT_MAX_NUM_BATCHED_TOKENS}" \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
  +actor_rollout_ref.ref.use_remove_padding=False \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.ref.fsdp_config.param_offload=True \
  distillation.enabled=True \
  distillation.n_gpus_per_node="${TEACHER_N_GPUS}" \
  distillation.nnodes=1 \
  distillation.teacher_models.teacher_model.model_path="${TEACHER_MODEL}" \
  distillation.teacher_models.teacher_model.num_replicas=1 \
  distillation.teacher_models.teacher_model.inference.name=vllm \
  distillation.teacher_models.teacher_model.inference.tensor_model_parallel_size="${TEACHER_TENSOR_MODEL_PARALLEL_SIZE}" \
  distillation.teacher_models.teacher_model.inference.temperature=1.0 \
  distillation.teacher_models.teacher_model.inference.gpu_memory_utilization="${TEACHER_GPU_MEMORY_UTILIZATION}" \
  distillation.teacher_models.teacher_model.inference.enforce_eager="${TEACHER_ENFORCE_EAGER}" \
  distillation.teacher_models.teacher_model.inference.max_num_batched_tokens="${TEACHER_MAX_NUM_BATCHED_TOKENS}" \
  distillation.teacher_models.teacher_model.inference.max_model_len=3073 \
  distillation.distillation_loss.loss_mode=forward_kl_topk \
  distillation.distillation_loss.topk=16 \
  distillation.distillation_loss.use_task_rewards="${DISTILLATION_USE_TASK_REWARDS}" \
  distillation.distillation_loss.distillation_loss_coef="${DISTILLATION_COEF}" \
  distillation.distillation_loss.use_policy_gradient=False \
  distillation.distillation_loss.loss_max_clamp=10.0 \
  distillation.distillation_loss.log_prob_min_clamp=-10.0 \
  trainer.logger='["console","tensorboard"]' \
  trainer.project_name=agopd-rl \
  trainer.experiment_name="${EXPERIMENT_NAME:-grpo_vanilla_opd_50step}" \
  trainer.n_gpus_per_node="${STUDENT_GPUS}" \
  trainer.nnodes=1 \
  trainer.save_freq="${SAVE_FREQ}" \
  trainer.test_freq=-1 \
  trainer.val_before_train=false \
  trainer.total_epochs="${TOTAL_EPOCHS}" \
  trainer.total_training_steps="${TRAIN_STEPS}" \
  trainer.rollout_data_dir="${OUTPUT_DIR}/rollouts" \
  +ray_kwargs.ray_init.runtime_env.env_vars.PYTHONPATH="${RAY_PYTHONPATH}" \
  "$@"
